version: "3.9"
 
services:
  db:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: this-is-the-mysql-root-user-password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: this-is-the-wordpress-user-password
 
  wordpress:
    depends_on:
      - db
    image: wordpress-image
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: this-is-the-wordpress-user-password
    volumes:
      - type: bind
        source: /path/to/host/folder
        target: /path/to/container/folder
 
volumes:
  db_data: {}
